# Generated by Django 4.0.5 on 2022-06-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_notasaulas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aulas',
            name='aula',
            field=models.CharField(max_length=255),
        ),
    ]
